frontend:
  build: ./docker/nginx/
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
  volumes_from:
    - static
web:
  build: .
  command: cds --debug run -h 0.0.0.0 -p 5000
  ports:
    - "5000:5000"
  environment:
    - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
    - "APP_BROKER_URL=amqp://guest:guest@mq:5672//"
    - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
    - "APP_CACHE_TYPE=redis"
    - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
    - "APP_SEARCH_ELASTIC_HOSTS=es:9200"
    - "APP_SECRET_KEY=CHANGE_ME"
    - "APP_SQLALCHEMY_DATABASE_URI=postgresql://cds:cds@db/cds"
  links:
    - cache
    - es
    - mq
    - db
  volumes_from:
    - static
worker:
  build: .
  command: "celery worker -A cds.celery --loglevel=INFO"
  environment:
    - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
    - "APP_BROKER_URL=amqp://guest:guest@mq:5672//"
    - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
    - "APP_CACHE_TYPE=redis"
    - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
    - "APP_SEARCH_ELASTIC_HOSTS=es:9200"
    - "APP_SECRET_KEY=CHANGE_ME"
    - "APP_SQLALCHEMY_DATABASE_URI=postgresql://cds:cds@db/cds"
  links:
    - cache
    - es
    - mq
    - db
  volumes_from:
    - static
cache:
  image: redis
  read_only: true
  ports:
    - "6379:6379"
db:
  image: postgres
  command: postgres
  environment:
    - "POSTGRES_USER=cds"
    - "POSTGRES_PASSWORD=cds"
    - "POSTGRES_DB=cds"
  ports:
    - "5432:5432"
  read_only: false
mq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
  read_only: true
es:
  build: ./docker/es/
  ports:
    - "9200:9200"
    - "9300:9300"
static:
  build: .
  command: /bin/true
  user: cds
  volumes:
    - "/usr/local/var/instance/static"
    - ".:/code/cds"
